### PR TITLE
Css canvas medical | Matt Powers

### PR DESCRIPTION
**Pull request by mpowers1113**
Screen Shot 2021-10-09 at 10 20 18 AM

### CODE REVIEW

**Comment by mpowers1113** [comment]
https://user-images.githubusercontent.com/88848572/136673449-0e0ce372-d23e-4f3e-bbd4-57b68706ad6d.mp4

**Comment by mpowers1113** [comment]
https://user-images.githubusercontent.com/88848572/136701976-475a9f2e-4782-47ab-982f-2781dbde26fb.mp4

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Fantastic work on this man!! I see a few things that need to be addressed, though:

1. You have quite a few variants of the "`row`" class in your CSS, you should separate each of those out into individual separate CSS classes you can apply in addition to the `row` class, which should have only the styling `display: flex`.
2. You have some variants of `column` classes too, and some seem to be named after their content rather than their size. Make sure you keep `column` classes to only `flex-basis` or `-width`, and shift any additional styling necessary to a new class.

Get started on revising these points, and once you get a new version turned in, I'll take a closer look to find more feedback for you. Again, great work on this!

**Comment by mpowers1113** [comment]
Thanks! I'm feeling way better about css

**Pull request merged**
